const APIPaths = {
  organizationListGet: "/organization/list",
  organizationAdd: "/organization/add",
  organizationEdit: "/organization/edit",
  communityList: "/community/list",
  communityGET: "/community/list",
  communityAdd: "/community/add",
  communityEdit: "/community/edit",
  addressList: "/address/list",
  addressAdd: "/address/add",
  countryList: "/country/list",
  stateList: "/state/list",
  timezoneList: "/timezone/list",
  personDataGet: "/user/getDetail",
  licenseList: "/license/list",
  licenseAdd: "/license/add",
  licenseEdit: "/license/edit",
  gameList: "/game/list",
  pricingPlanList: "/pricingPlan/list",
  pricingPlanAdd: "/pricingPlan/add",
  pricingPlanEdit: "/pricingPlan/edit",
  orgCommunityPay: "/orgCommPay/list",
  userList: "/user/list",
  userSearch:"/user/search",
  userAdd:"/user/add",
  userEdit:"/user/edit",
  hostList:"user/hostList",
  gameAdd: "/game/add",
  gameEdit: "/game/edit",
  puzzlecategoryList: "/puzzle/categoryList",
  puzzleAddCategory: "/puzzle/addCategory",
  puzzleEditCategory: "/puzzle/editCategory",
  puzzleList: "/puzzle/list",
  gameLevelList: "/game/levelList",
  puzzleAdd: "/puzzle/add",
  puzzleEdit: "/puzzle/edit",
  roleList: "/role/list",
  roleAdd: "/role/add",
  roleEdit: "/role/edit",
  gameScheduleAdd:"/gameSchedule/add",
  gameSCheduleEdit:"/gameSchedule/edit",
  gamePlayerDetails:"/gameSchedule/playerDetails",
  customSpinnerList:"/customeSpinner/list",
  gameSchedulePuzzleCategoryList: "/gameSchedule/puzzleCategoryList",
  gamesPlayedList: "/gameSchedule/gamesPlayed",
  gameScheduleList: "/gameSchedule/list",
  getDetail:"/user/getDetail",
  organizationReportList:"/report/organizationList",
  getLicenseList:"/report/licenseList",
  attendanceList:"/gameSchedule/attendanceList",
  recordAttendance:"/gameSchedule/recordAttendance",
  rateHost:"/gameSchedule/rateHost",
  roleReport:"/report/roleList",
  startGame: "/gameSchedule/start",
  participantTypeList: "/gameSchedule/participantTypeList",
  contactSupport:'/contact/support',
  contactCategory:'/contact/categoryList',
  getPuzzleList:"/report/puzzleList",
  getPersonsList:"/report/personList",
  startMeeting: "/gameSchedule/startMeeting",
  getPuzzlePlayedList:"/gameSchedule/puzzlesPlayed",
  rateHostDetails:"/gameSchedule/rateHostDetail"
};

export default APIPaths;
